---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: app-pipeline
  namespace: {{ .Values.certificate.namespace }}
spec:
  secretName: app-pipeline-cert
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: {{ .Values.certificate.kind }}
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
  {{- toYaml .Values.certificate.dnsNames | nindent 2 }}
---
