apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: app-pipeline
  namespace: tekton-pipelines 
spec:
  serviceAccountName: app-pipeline-tekton-github-triggers
  triggers:
  - name: github-listener
    interceptors:
    - github:
        secretRef:
          secretName: app-pipeline-webhook-secret
          secretKey: secretToken
        eventTypes:
        - push
    - cel:
        filter: "body.ref == 'refs/heads/master'"
    bindings:
    - name: app-pipeline
    template:
      name: app-pipeline
---
