---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "app-pipeline.fullname" . }}-github-ssh-key
spec:
  backendType: vault
  vaultMountPoint: app
  vaultRole: kes
  data:
  - name: ssh-privatekey
    key: {{ .Values.github.githubVaultSecret }}
    property: {{ .Values.github.privateKeyProperty }}
  template:
    type: kubernetes.io/ssh-auth
    metadata:
      annotations:
        tekton.dev/git-0: github.com
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "app-pipeline.fullname" . }}-docker-creds
  namespace: tekton-pipelines
spec:
  backendType: vault
  vaultMountPoint: app
  vaultRole: kes
  data:
  - name: username
    key: {{ .Values.registry.registryVaultSecret }}
    property: {{ .Values.registry.usernameProperty }}
  - name: password
    key: {{ .Values.registry.registryVaultSecret }}
    property: {{ .Values.registry.passwordProperty }}
  - name: email
    key: {{ .Values.registry.registryVaultSecret }}
    property: {{ .Values.registry.emailProperty }}
  template:
    type: kubernetes.io/basic-auth
    metadata:
      annotations:
        tekton.dev/docker-0: {{ .Values.registry.url }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "app-pipeline.fullname" . }}-webhook-secret
spec:
  backendType: vault
  vaultMountPoint: app
  vaultRole: kes
  data:
  - name: secretToken
    key: {{ .Values.github.githubVaultSecret }}
    property: {{ .Values.github.secretProperty }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "app-pipeline.fullname" . }}-argocd-secret
  namespace: tekton-pipelines
spec:
  backendType: vault
  vaultMountPoint: app
  vaultRole: kes
  data:
  - name: username
    key: {{ .Values.argocd.argocdVaultSecret }}
    property: {{ .Values.argocd.usernameProperty }}
  - name: password
    key: {{ .Values.argocd.argocdVaultSecret }}
    property: {{ .Values.argocd.passwordProperty }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "app-pipeline.fullname" . }}-docker-creds
  namespace: production
spec:
  backendType: vault
  vaultMountPoint: app
  vaultRole: kes
  data:
  - name: username
    key: {{ .Values.registry.registryVaultSecret }}
    property: {{ .Values.registry.usernameProperty }}
  - name: password
    key: {{ .Values.registry.registryVaultSecret }}
    property: {{ .Values.registry.passwordProperty }}
  - name: email
    key: {{ .Values.registry.registryVaultSecret }}
    property: {{ .Values.registry.emailProperty }}
  template:
    type: kubernetes.io/basic-auth
    metadata:
      annotations:
        tekton.dev/docker-0: {{ .Values.registry.url }}
---
