---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-pipeline
  namespace: tekton-pipelines 
spec:
  selector:
    istio: {{ .Values.istio.istioSelector }}
  servers:
  - port:
      number: {{ .Values.istio.port }}
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "app-pipeline-cert"
    hosts:
      {{- toYaml .Values.certificate.dnsNames | nindent 4 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-pipeline
  namespace: tekton-pipelines
spec:
  hosts:
    {{- toYaml .Values.certificate.dnsNames | nindent 4 }} 
  gateways:
  - app-pipeline
  http:
  - route:
    - destination:
        host: el-app-pipeline
        port:
          number: 8080
