kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "app-pipeline.fullname" . }}-tekton-github-triggers
  namespace: tekton-pipelines
  labels:
    {{- include "app-pipeline.labels" . | nindent 4 }}  
secrets:
- name: {{ include "app-pipeline.fullname" . }}-webhook-secret
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app-pipeline.fullname" . }}-tekton-github-triggers-binding
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: {{ include "app-pipeline.fullname" . }}-tekton-github-triggers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "app-pipeline.fullname" . }}-tekton-github-triggers
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app-pipeline.fullname" . }}-tekton-github-triggers
  namespace: tekton-pipelines
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  # secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
  resources: ["configmaps", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
---
