apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-pipeline.fullname" . }}
  namespace: tekton-pipelines
secrets:
- name: {{ include "app-pipeline.fullname" . }}-docker-creds
- name: {{ include "app-pipeline.fullname" . }}-github-ssh-key
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "app-pipeline.fullname" . }}
  namespace: tekton-pipelines
rules:
- apiGroups: ["serving.knative.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["eventing.knative.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["sources.eventing.knative.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "app-pipeline.fullname" . }}
  namespace: tekton-pipelines
roleRef:
  kind: Role
  name: {{ include "app-pipeline.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "app-pipeline.fullname" . }}
  namespace: tekton-pipelines
---
