apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-pipeline
  namespace: tekton-pipelines   
spec:
  params:
  - name: buildRevision
    description: The Git commit revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: app-pipeline-build-deploy-
    spec:
      pipelineRef:
        name: app-pipeline
      serviceAccountName: app-pipeline
      params:
      - name: buildRevision
        value: $(tt.params.buildRevision)
      - name: appGitUrl
        value: {{ .Values.pipelineRun.appGitUrl }}
      - name: configGitUrl
        value: {{ .Values.pipelineRun.configGitUrl }}
      - name: appImage
        value: {{ .Values.pipelineRun.appImage }}
      workspaces:
      - name: app-source
        emptyDir: {}
      - name: config-source
        emptyDir: {}
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: app-pipeline    
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    value: $(body.head_commit.id)
---
