---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: grafana
  namespace: istio-system
spec:
  backendType: vault
  vaultMountPoint: {{ .Values.vault.mountPoint }}
  vaultRole: {{ .Values.vault.role }}
  data:
  - name: username
    key: {{ .Values.grafana.username.key }}
    property: {{ .Values.grafana.username.property }}
  - name: passphrase
    key: {{ .Values.grafana.passphrase.key }}
    property: {{ .Values.grafana.passphrase.property }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: kiali
  namespace: istio-system
spec:
  backendType: vault
  vaultMountPoint: {{ .Values.vault.mountPoint }}
  vaultRole: {{ .Values.vault.role }}
  data:
  - name: username
    key: {{ .Values.kiali.username.key }}
    property: {{ .Values.kiali.username.property }}
  - name: passphrase
    key: {{ .Values.kiali.passphrase.key }}
    property: {{ .Values.kiali.passphrase.property }}
