---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: hello-cert
spec:
  secretName: hello-cert
  issuerRef:
    name: letsencrypt-staging-istio
    kind: ClusterIssuer
  commonName: hello.bahkuyt.tech
  dnsNames:
  - hello.bahkuyt.tech
---