apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vault-cert
  namespace: istio-system
spec:
  secretName: vault-cert
  issuerRef:
    name: letsencrypt-prod-istio
    kind: ClusterIssuer
  commonName: {{ .Values.commonName }}
  dnsNames:
  {{- toYaml .Values.dnsNames | nindent 2 }}
---