apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-pipeline
  namespace: argocd
spec:
  destination:
    namespace: tekton-pipelines
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .Values.appPipelines.path }}
    repoURL: {{ .Values.appPipelines.repoUrl }}
    targetRevision: {{ .Values.appPipelines.targetRevision }}
  syncPolicy:
    automated: {}
---
