apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .Values.app.path }}
    repoURL: {{ .Values.app.repoUrl }}
    targetRevision: {{ .Values.app.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
