vault:
  mountPoint: kes
  role: kes

grafana:
  username:
    key: kes/data/istio/grafana-user
    property: username
  passphrase:
    key: kes/data/istio/grafana-user
    property: passphrase

kiali: 
  username:
    key: kes/data/istio/kiali-user
    property: username
  passphrase:
    key: kes/data/istio/kiali-user
    property: passphrase